# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\settings_functions_stacked_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(380, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StackedWidget.sizePolicy().hasHeightForWidth())
        StackedWidget.setSizePolicy(sizePolicy)
        StackedWidget.setStyleSheet("")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.page)
        self.toolBox.setObjectName("toolBox")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 358, 996))
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.path_le = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_le.sizePolicy().hasHeightForWidth())
        self.path_le.setSizePolicy(sizePolicy)
        self.path_le.setObjectName("path_le")
        self.horizontalLayout_4.addWidget(self.path_le)
        self.open_file_btn = QtWidgets.QToolButton(self.page_2)
        self.open_file_btn.setObjectName("open_file_btn")
        self.horizontalLayout_4.addWidget(self.open_file_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.path_warning_label = QtWidgets.QLabel(self.page_2)
        self.path_warning_label.setText("")
        self.path_warning_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.path_warning_label.setWordWrap(True)
        self.path_warning_label.setObjectName("path_warning_label")
        self.verticalLayout.addWidget(self.path_warning_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.encoding_le = QtWidgets.QLineEdit(self.page_2)
        self.encoding_le.setText("")
        self.encoding_le.setObjectName("encoding_le")
        self.horizontalLayout.addWidget(self.encoding_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.size_le = QtWidgets.QLineEdit(self.page_2)
        self.size_le.setObjectName("size_le")
        self.horizontalLayout_5.addWidget(self.size_le)
        self.size_label = QtWidgets.QLabel(self.page_2)
        self.size_label.setObjectName("size_label")
        self.horizontalLayout_5.addWidget(self.size_label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.record_num_label = QtWidgets.QLabel(self.page_2)
        self.record_num_label.setObjectName("record_num_label")
        self.horizontalLayout_2.addWidget(self.record_num_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.csv_settings_widget = QtWidgets.QWidget(self.page_2)
        self.csv_settings_widget.setEnabled(True)
        self.csv_settings_widget.setObjectName("csv_settings_widget")
        self.csv_settings_layout = QtWidgets.QHBoxLayout(self.csv_settings_widget)
        self.csv_settings_layout.setObjectName("csv_settings_layout")
        self.label_2 = QtWidgets.QLabel(self.csv_settings_widget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.csv_settings_layout.addWidget(self.label_2)
        self.csv_header_le = QtWidgets.QLineEdit(self.csv_settings_widget)
        self.csv_header_le.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_header_le.sizePolicy().hasHeightForWidth())
        self.csv_header_le.setSizePolicy(sizePolicy)
        self.csv_header_le.setObjectName("csv_header_le")
        self.csv_settings_layout.addWidget(self.csv_header_le)
        self.label_3 = QtWidgets.QLabel(self.csv_settings_widget)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.csv_settings_layout.addWidget(self.label_3)
        self.csv_seperator_le = QtWidgets.QLineEdit(self.csv_settings_widget)
        self.csv_seperator_le.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_seperator_le.sizePolicy().hasHeightForWidth())
        self.csv_seperator_le.setSizePolicy(sizePolicy)
        self.csv_seperator_le.setObjectName("csv_seperator_le")
        self.csv_settings_layout.addWidget(self.csv_seperator_le)
        self.verticalLayout.addWidget(self.csv_settings_widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.sample_records_le = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_records_le.sizePolicy().hasHeightForWidth())
        self.sample_records_le.setSizePolicy(sizePolicy)
        self.sample_records_le.setObjectName("sample_records_le")
        self.horizontalLayout_3.addWidget(self.sample_records_le)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 358, 996))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        StackedWidget.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        StackedWidget.addWidget(self.page1)
        self.label.setBuddy(self.path_le)
        self.label_4.setBuddy(self.sample_records_le)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.open_file_btn.clicked.connect(StackedWidget.add_path_slot)
        self.path_le.textChanged['QString'].connect(StackedWidget.parse_path_slot)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.label.setText(_translate("StackedWidget", "Path/URI:"))
        self.open_file_btn.setText(_translate("StackedWidget", "..."))
        self.label_7.setText(_translate("StackedWidget", "Encoding: "))
        self.label_9.setText(_translate("StackedWidget", "Size:"))
        self.size_label.setText(_translate("StackedWidget", "KB"))
        self.label_5.setText(_translate("StackedWidget", "Num of Records:"))
        self.record_num_label.setText(_translate("StackedWidget", "0"))
        self.label_2.setText(_translate("StackedWidget", "Header:"))
        self.csv_header_le.setText(_translate("StackedWidget", "1"))
        self.label_3.setText(_translate("StackedWidget", "Separator:"))
        self.csv_seperator_le.setText(_translate("StackedWidget", ","))
        self.label_4.setText(_translate("StackedWidget", "Sample"))
        self.comboBox.setItemText(0, _translate("StackedWidget", "first"))
        self.comboBox.setItemText(1, _translate("StackedWidget", "random"))
        self.label_8.setText(_translate("StackedWidget", "records"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("StackedWidget", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("StackedWidget", "Page 2"))

